services:
  db-user:
        container_name: db-user
        hostname: db-user
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        image: postgres:latest
        networks:
            - main
        expose:
            - "5432:5432"
        restart: on-failure
        volumes:
            - db-user-data:/var/lib/postgresql/data
  app-user:
        build: ./services/user-service
        command: sh -c "npm run dbMigrate && npm run dbSeed && npm run start"
        ports: 
            - "3001:3001"
        depends_on:
            - db-user
        networks: 
            - main
        restart: on-failure
networks:
    main:
volumes:
    db-user-data: